const GST_RATE=0.08;
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const money=n=>`MVR ${Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const cleanNumber=v=>Math.max(0,Number(v)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[];
function newItem(description='',qty=1,price=0){items.push({id:crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random(),description,qty,price});renderItems();}
function renderItems(){
 const body=$('#itemsBody'); body.innerHTML='';
 items.forEach((it,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td><input aria-label="Item ${i+1} description" data-key="description" data-id="${it.id}" value="${esc(it.description)}" placeholder="Item description"></td><td><input aria-label="Quantity" data-key="qty" data-id="${it.id}" type="number" min="0" step="1" value="${it.qty}"></td><td><input aria-label="Unit price" data-key="price" data-id="${it.id}" type="number" min="0" step="0.01" value="${it.price}"></td><td class="items-table-total">${money(it.qty*it.price)}</td><td><button class="remove" data-remove="${it.id}" title="Remove item">×</button></td>`;body.appendChild(tr)});
 body.querySelectorAll('input').forEach(el=>el.addEventListener('input',e=>{const it=items.find(x=>String(x.id)===e.target.dataset.id);it[e.target.dataset.key]=e.target.dataset.key==='description'?e.target.value:cleanNumber(e.target.value);renderPreview();e.target.closest('tr').querySelector('.items-table-total').textContent=money(it.qty*it.price)}));
 body.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{items=items.filter(x=>String(x.id)!==b.dataset.remove);if(!items.length)newItem();else renderItems()}));renderPreview();
}
function values(){return {quoteNo:$('#quoteNo').value.trim(),quoteDate:$('#quoteDate').value,customerName:$('#customerName').value.trim(),customerContact:$('#customerContact').value.trim(),customerAddress:$('#customerAddress').value.trim(),terms:$('#terms').value.trim()}}
function totals(){const subtotal=items.reduce((s,x)=>s+cleanNumber(x.qty)*cleanNumber(x.price),0);const gst=subtotal*GST_RATE;return{subtotal,gst,grand:subtotal+gst}}
function renderPreview(){const v=values(),t=totals();$$('[data-preview]').forEach(el=>{const key=el.dataset.preview;let val=v[key]||'';if(key==='quoteDate'&&val)val=new Date(val+'T00:00:00').toLocaleDateString('en-GB');if(key==='customerName'&&!val)val='Customer name';if(key==='quoteNo'&&!val)val='-';el.textContent=val});
 $('#previewItems').innerHTML=items.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.description)||'—'}</td><td>${x.qty}</td><td>${money(x.price)}</td><td>${money(x.qty*x.price)}</td></tr>`).join('');
 $('#subtotal').textContent=$('#pSubtotal').textContent=money(t.subtotal);$('#gst').textContent=$('#pGst').textContent=money(t.gst);$('#grandTotal').textContent=$('#pGrand').textContent=money(t.grand);
}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1900)}
function save(){localStorage.setItem('imasterQuotation',JSON.stringify({...values(),items}));$('#saveStatus').textContent='Draft saved locally';toast('Draft saved in this browser')}
function load(){try{const d=JSON.parse(localStorage.getItem('imasterQuotation'));if(!d)return false;['quoteNo','quoteDate','customerName','customerContact','customerAddress','terms'].forEach(k=>{if(d[k]!=null)$('#'+k).value=d[k]});items=Array.isArray(d.items)?d.items:[];return true}catch{return false}}
function reset(){localStorage.removeItem('imasterQuotation');$('#quoteNo').value=`Q-${new Date().getFullYear()}-001`;$('#quoteDate').value=new Date().toISOString().slice(0,10);$('#customerName').value='';$('#customerContact').value='';$('#customerAddress').value='';$('#terms').value='1. This quotation is valid for 14 days.\n2. Payment terms are subject to agreement.\n3. Goods sold are subject to availability.';items=[];newItem();$('#saveStatus').textContent='New quotation';toast('New quotation started')}
function latin(s){return String(s??'').normalize('NFKD').replace(/[^\x20-\x7E]/g,'?')}
function pdfEscape(s){return latin(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function wrap(text,max=74){const out=[];String(text||'').split(/\n/).forEach(p=>{let line='';p.split(/\s+/).forEach(w=>{if((line+' '+w).trim().length>max){if(line)out.push(line);line=w}else line=(line+' '+w).trim()});out.push(line)});return out}
function downloadPDF(){
 const v=values(),t=totals();if(!v.quoteNo||!v.customerName){toast('Enter quotation number and customer name');return}
 let pages=[],ops=[],y=805;const add=(txt,x,size=10,bold=false)=>{ops.push(`BT /F${bold?2:1} ${size} Tf ${x} ${y} Td (${pdfEscape(txt)}) Tj ET`)};const line=(x1,y1,x2,y2,w=1)=>ops.push(`${w} w ${x1} ${y1} m ${x2} ${y2} l S`);const page=()=>{pages.push(ops.join('\n'));ops=[];y=805};const need=h=>{if(y-h<55){page();y=805;add('iMaster - Quotation '+v.quoteNo,45,12,true);y-=28}};
 add('iMaster',45,24,true);add('QUOTATION',410,18,true);y-=19;add('Contact: 7700420',45,10);add('No: '+v.quoteNo,410,10);y-=15;add('Date: '+(v.quoteDate||'-'),410,10);y-=16;line(45,y,550,y,2);y-=30;add('BILL TO',45,9,true);y-=18;add(v.customerName,45,13,true);y-=16;if(v.customerContact){add('Contact: '+v.customerContact,45);y-=14}wrap(v.customerAddress,80).forEach(s=>{if(s){add(s,45);y-=13}});y-=15;
 add('#',48,9,true);add('Description',78,9,true);add('Qty',390,9,true);add('Unit Price',430,9,true);add('Total',505,9,true);y-=9;line(45,y,550,y,1);y-=18;
 items.forEach((it,i)=>{const lines=wrap(it.description||'-',48);need(Math.max(22,lines.length*13));add(String(i+1),48);lines.forEach((s,j)=>{add(s,78);if(j<lines.length-1)y-=13});add(String(it.qty),400);add(money(it.price).replace('MVR ','') ,445);add(money(it.qty*it.price).replace('MVR ',''),510);y-=20;line(45,y+7,550,y+7,.3)});
 need(150);y-=12;add('Subtotal: '+money(t.subtotal),390,10,true);y-=18;add('GST (8%): '+money(t.gst),390,10,true);y-=20;line(385,y+8,550,y+8,1);add('Grand Total: '+money(t.grand),365,13,true);y-=40;add('Terms & Conditions',45,10,true);y-=17;wrap(v.terms,76).forEach(s=>{need(15);add(s,45,8);y-=12});y-=48;line(390,y,535,y,.7);y-=15;add('Authorized Signature',414,9);y-=35;add('Thank you for choosing iMaster.',205,9);page();
 const objects=[];const push=s=>{objects.push(s);return objects.length};const font1=push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const font2=push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');const contentIds=pages.map(p=>push(`<< /Length ${p.length} >>\nstream\n${p}\nendstream`));const pageIds=[];const pagesId=objects.length+contentIds.length+1+pages.length;contentIds.forEach(cid=>pageIds.push(push(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${cid} 0 R >>`)));const actualPagesId=push(`<< /Type /Pages /Kids [${pageIds.map(id=>id+' 0 R').join(' ')}] /Count ${pageIds.length} >>`);pageIds.forEach(id=>objects[id-1]=objects[id-1].replace(`/Parent ${pagesId} 0 R`,`/Parent ${actualPagesId} 0 R`));const catalog=push(`<< /Type /Catalog /Pages ${actualPagesId} 0 R >>`);
 let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;
 const blob=new Blob([pdf],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`iMaster_${v.quoteNo.replace(/[^a-z0-9_-]/gi,'_')}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('PDF downloaded')
}
$('#addItemBtn').addEventListener('click',()=>newItem());$('#saveBtn').addEventListener('click',save);$('#printBtn').addEventListener('click',()=>window.print());$('#pdfBtn').addEventListener('click',downloadPDF);$('#newBtn').addEventListener('click',reset);$$('input,textarea').forEach(e=>e.addEventListener('input',renderPreview));if(!load())reset();else{renderItems();$('#saveStatus').textContent='Saved draft loaded'}
